<?php
	//diretуrio destino das imagens dentro da pasta da aplicaзгo...
	//deve ter permissгo para escrita chmod(777)...
	$dir = "../fotos/";
	//recebendo o arquivo multipart vindo do flash...
	$file = $_FILES["Filedata"];
	//finalizando o upload e criando apartir do arquivo temp, multipart, um novo arquivo
	// em nossa pasta de destino. O echo serve para dizer ao flash se deu certo ou nгo...
	echo move_uploaded_file($file["tmp_name"], $dir . "/" . $file["name"]);
?>